In [77]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [78]:
df_train = pd.read_csv("D:\\Aniket\\Kaggle_Competition\\House_Price_Advance\\train.csv")
df_test = pd.read_csv("D:\\Aniket\\Kaggle_Competition\\House_Price_Advance\\test.csv")

In [79]:
df_train.head()

   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape LandContour Utilities LotConfig LandSlope Neighborhood Condition1 Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea PoolQC Fence MiscFeature  MiscVal  MoSold  YrSold SaleType SaleCondition  SalePrice
0   1          60       RL         65.0     8450   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl      CollgCr       Norm       Norm     1Fam     2Story            7            5       2003          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace       196.0        Gd        TA      PConc       Gd       TA           No          GLQ         706          Unf           0        150          856    GasA        Ex          Y      SBrkr       856       854             0       1710             1             0         2         1             3             1          Gd             8        Typ           0         NaN     Attchd       2003.0          RFn           2         548         TA         TA          Y           0           61              0          0            0         0    NaN   NaN         NaN        0       2    2008       WD        Normal     208500
1   2          20       RL         80.0     9600   Pave   NaN      Reg         Lvl    AllPub       FR2       Gtl      Veenker      Feedr       Norm     1Fam     1Story            6            8       1976          1976     Gable  CompShg     MetalSd     MetalSd        NaN         0.0        TA        TA     CBlock       Gd       TA           Gd          ALQ         978          Unf           0        284         1262    GasA        Ex          Y      SBrkr      1262         0             0       1262             0             1         2         0             3             1          TA             6        Typ           1          TA     Attchd       1976.0          RFn           2         460         TA         TA          Y         298            0              0          0            0         0    NaN   NaN         NaN        0       5    2007       WD        Normal     181500
2   3          60       RL         68.0    11250   Pave   NaN      IR1         Lvl    AllPub    Inside       Gtl      CollgCr       Norm       Norm     1Fam     2Story            7            5       2001          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace       162.0        Gd        TA      PConc       Gd       TA           Mn          GLQ         486          Unf           0        434          920    GasA        Ex          Y      SBrkr       920       866             0       1786             1             0         2         1             3             1          Gd             6        Typ           1          TA     Attchd       2001.0          RFn           2         608         TA         TA          Y           0           42              0          0            0         0    NaN   NaN         NaN        0       9    2008       WD        Normal     223500
3   4          70       RL         60.0     9550   Pave   NaN      IR1         Lvl    AllPub    Corner       Gtl      Crawfor       Norm       Norm     1Fam     2Story            7            5       1915          1970     Gable  CompShg     Wd Sdng     Wd Shng        NaN         0.0        TA        TA     BrkTil       TA       Gd           No          ALQ         216          Unf           0        540          756    GasA        Gd          Y      SBrkr       961       756             0       1717             1             0         1         0             3             1          Gd             7        Typ           1          Gd     Detchd       1998.0          Unf           3         642         TA         TA          Y           0           35            272          0            0         0    NaN   NaN         NaN        0       2    2006       WD       Abnorml     140000
4   5          60       RL         84.0    14260   Pave   NaN      IR1         Lvl    AllPub       FR2       Gtl      NoRidge       Norm       Norm     1Fam     2Story            8            5       2000          2000     Gable  CompShg     VinylSd     VinylSd    BrkFace       350.0        Gd        TA      PConc       Gd       TA           Av          GLQ         655          Unf           0        490         1145    GasA        Ex          Y      SBrkr      1145      1053             0       2198             1             0         2         1             4             1          Gd             9        Typ           1          TA     Attchd       2000.0          RFn           3         836         TA         TA          Y         192           84              0          0            0         0    NaN   NaN         NaN        0      12    2008       WD        Normal     250000

In [80]:
print(df_train.shape)
print(df_test.shape)

(1460, 81)
(1459, 80)

In [81]:
print(df_train.isnull().sum())

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [82]:
df_test.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       227
LotArea             0
Street              0
Alley            1352
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
MasVnrType        894
MasVnrArea         15
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           44
BsmtCond           45
BsmtExposure       44
BsmtFinType1       42
BsmtFinSF1          1
BsmtFinType2       42
BsmtFinSF2          1
BsmtUnfSF           1
TotalBsmtSF         1
Heating             0
HeatingQC           0
CentralAir          0
Electrical          0
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        2
BsmtHalfBath        2
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         1
TotRmsAbvGrd        0
Functional          2
Fireplaces          0
FireplaceQu       730
GarageType         76
GarageYrBlt        78
GarageFinish       78
GarageCars          1
GarageArea          1
GarageQual         78
GarageCond         78
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1456
Fence            1169
MiscFeature      1408
MiscVal             0
MoSold              0
YrSold              0
SaleType            1
SaleCondition       0
dtype: int64

In [83]:
df_train.drop(columns={"PoolQC","Fence","MiscFeature","FireplaceQu","MasVnrType","Alley","LotFrontage"}, inplace=True)

In [84]:
df_test.drop(columns={"PoolQC","Fence","MiscFeature","FireplaceQu","MasVnrType","Alley","LotFrontage"}, inplace=True)

## Plots

In [85]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import math
import numpy as np

def plot_distributions(df, columns=None, cols_per_row=3, save_prefix='distribution'):
    """
    Plots the distribution (histogram + KDE) for numerical columns in a grid layout.
    Saves the cohesive plot grid directly to a PNG file.
    """
    # Automatically select all numerical columns if none are provided
    if columns is None:
        columns = df.select_dtypes(include=['number']).columns.tolist()
    
    num_plots = len(columns)
    if num_plots == 0:
        print("No numerical columns found to plot.")
        return
    
    # Calculate rows required based on the requested columns per row
    rows = math.ceil(num_plots / cols_per_row)
    
    # Create grid using subplots (avoids plt.figure() overlapping limitations)
    fig, axes = plt.subplots(rows, cols_per_row, figsize=(cols_per_row * 4, rows * 3.5))
    
    # Uniformly handle single-plot vs multi-plot axes layouts
    if num_plots == 1:
        axes = [axes]
    else:
        axes = axes.flatten()
        
    for i, col in enumerate(columns):
        sns.histplot(data=df, x=col, kde=True, ax=axes[i], color='skyblue')
        axes[i].set_title(f'Distribution of {col}', fontsize=11)
        axes[i].set_xlabel('')
        axes[i].set_ylabel('Count / Density')
        
    # Automatically clean up and delete unused blank subplots in the grid boundary
    for j in range(i + 1, len(axes)):
        fig.delaxes(axes[j])
        
    plt.tight_layout()
    output_filename = f"{save_prefix}_grid.png"
    plt.savefig(output_filename, dpi=300, bbox_inches='tight')
    print(f"Distribution plot successfully saved as: {output_filename}")

def get_correlation(df, feature1, feature2, method='pearson'):
    """
    Calculates and returns the specific correlation coefficient between two columns.
    Supported methods: 'pearson', 'spearman', 'kendall'
    """
    if feature1 not in df.columns or feature2 not in df.columns:
        raise ValueError(f"Error: One or both features ('{feature1}', '{feature2}') do not exist in the DataFrame.")
        
    # Drop records containing missing values in either targeted column
    clean_df = df[[feature1, feature2]].dropna()
    
    if clean_df.empty:
        print("Warning: No overlapping non-null data exists between these two features.")
        return None
        
    # Calculate the correlation coefficient
    corr_value = clean_df[feature1].corr(clean_df[feature2], method=method)
    return corr_value

def plot_correlation_matrix(df, method='pearson', filename='correlation_matrix.png'):
    """
    Isolates all numerical features, calculates the correlation matrix, 
    and generates a visually optimized half-triangle heatmap.
    """
    numeric_df = df.select_dtypes(include=['number'])
    
    if numeric_df.empty:
        print("No numerical columns found in the dataset to build a correlation matrix.")
        return
        
    corr_matrix = numeric_df.corr(method=method)
    num_features = len(corr_matrix.columns)
    
    # Scale figure footprint dynamically based on the volume of attributes
    grid_size = max(6, num_features * 0.8)
    fig, ax = plt.subplots(figsize=(grid_size, grid_size * 0.8))
    
    # Construct an upper triangle boolean mask to strip mirror-image visual clutter
    mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
    
    # Dynamically scale text size inside squares to prevent overlapping text
    font_size = max(7, 12 - num_features // 3)
    
    sns.heatmap(
        corr_matrix, 
        mask=mask,
        annot=True, 
        fmt=".2f", 
        cmap='coolwarm', 
        vmin=-1,       # Anchored lower boundary for negative correlations
        vmax=1,        # Anchored upper boundary for positive correlations
        center=0,      # Perfectly balanced mid-point color neutrality
        square=True, 
        linewidths=.5, 
        cbar_kws={"shrink": .8},
        ax=ax,
        annot_kws={"size": font_size}
    )
    
    ax.set_title(f"Correlation Dashboard ({method.capitalize()}'s $r$)", fontsize=14, pad=20)
    plt.xticks(rotation=45, ha='right')
    plt.yticks(rotation=0)
    
    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    print(f"Correlation matrix heatmap successfully saved as: {filename}")

## Encoding

In [86]:
# 2. Define your specific mapping dictionary
zoning_map = {'A': 0, 'RP': 1, 'RL': 2, 'RM': 3, 'RH': 4, 'FV': 5, 'C': 6, 'I': 7}

# 3. Apply the mapping to replace the strings with integers
df_train['MSZoning'] = df_train['MSZoning'].map(zoning_map)
df_test['MSZoning'] = df_test['MSZoning'].map(zoning_map)

In [87]:
Street_map = {'Grvl': 0, 'Pave': 1}

df_train['Street'] = df_train['Street'].map(Street_map)
df_test['Street'] = df_test['Street'].map(Street_map)

In [88]:
LotShape_map = {'IR3':0, 'IR2':1, 'IR1':2, 'Reg':3}

df_train['LotShape'] = df_train['LotShape'].map(LotShape_map)
df_test['LotShape'] = df_test['LotShape'].map(LotShape_map)

In [89]:
contour_mapping = {
    'Low': 0,
    'HLS': 1,
    'Bnk': 2,
    'Lvl': 3
}

df_train['LandContour'] = df_train['LandContour'].map(contour_mapping)
df_test['LandContour'] = df_test['LandContour'].map(contour_mapping)

In [90]:
ordinal_mappings = {
    'Utilities': {'ELO': 0, 'NoSeWa': 1, 'NoSewr': 2, 'AllPub': 3},
    
    'LandSlope': {'Sev': 0, 'Mod': 1, 'Gtl': 2},
    
    'ExterQual': {'Po': 0, 'Fa': 1, 'TA': 2, 'Gd': 3, 'Ex': 4},
    
    'ExterCond': {'Po': 0, 'Fa': 1, 'TA': 2, 'Gd': 3, 'Ex': 4},
    
    'BsmtQual':  {'NA': 0, 'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5},
    
    'BsmtCond':  {'NA': 0, 'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5},
    
    'BsmtExposure': {'NA': 0, 'No': 1, 'Mn': 2, 'Av': 3, 'Gd': 4},
    
    'BsmtFinType1': {'NA': 0, 'Unf': 1, 'LwQ': 2, 'Rec': 3, 'BLQ': 4, 'ALQ': 5, 'GLQ': 6}
}

# Loop and map directly onto the dataframe
for col, mapping in ordinal_mappings.items():
    if col in df_train.columns:
        df_train[col] = df_train[col].map(mapping)

for col, mapping in ordinal_mappings.items():
    if col in df_test.columns:
        df_test[col] = df_test[col].map(mapping)

In [91]:
nominal_mappings = {
    # Premium given to privacy, low traffic, and wider yards
    'LotConfig': {'Inside': 0, 'Corner': 1, 'FR2': 2, 'FR3': 3, 'CulDSac': 4},
    
    # Premium given to detached structure and end-unit privacy
    'BldgType': {'TwnhsI': 0, 'Duplx': 1, '2FmCon': 2, 'TwnhsE': 3, '1Fam': 4},
    
    # Ranked by finished living style popularity and floorplan complexity
    'HouseStyle': {'1.5Unf': 0, '1.5Fin': 1, '2.5Unf': 2, '2.5Fin': 3, '1Story': 4, 'SFoyer': 5, 'SLvl': 6, '2Story': 7},
    
    # Ranked by construction and aesthetic complexity
    'RoofStyle': {'Shed': 0, 'Gambrel': 1, 'Flat': 2, 'Mansard': 3, 'Gable': 4, 'Hip': 5},
    
    # Material longevity, cost premium, and durability
    'RoofMatl': {'Roll': 0, 'Tar&Grv': 1, 'CompShg': 2, 'Membran': 3, 'Metal': 4, 'WdShake': 5, 'WdShngl': 6, 'ClyTile': 7},
    
    # Masonry material aesthetic values
    'MasVnrType': {'None': 0, 'CBlock': 1, 'BrkCmn': 2, 'BrkFace': 3, 'Stone': 4},
    
    # Modern poured concrete (PConc) and cinder blocks hold the best structural integrity
    'Foundation': {'Slab': 0, 'Wood': 1, 'Stone': 2, 'BrkTil': 3, 'CBlock': 4, 'PConc': 5}
}

for col,mapping in nominal_mappings.items():
    if col in df_train.columns:
        df_train[col] = df_train[col].map(mapping)

for col, mapping in nominal_mappings.items():
    if col in df_test.columns:
        df_test[col] = df_test[col].map(mapping)

In [93]:
from category_encoders import TargetEncoder # type:ignore

te = te = TargetEncoder(cols=['Neighborhood'])

# Fit on training data features (X) and target (y), then transform
df_train['Neighborhood'] = te.fit_transform(df_train['Neighborhood'], df_train['SalePrice'])

# Transform the test set using the calculated training rules
df_test['Neighborhood'] = te.transform(df_test['Neighborhood'])

In [94]:
print(df_train.shape)
print(df_test.shape)

(1460, 74)
(1459, 73)

In [95]:
df_train.head()

   Id  MSSubClass  MSZoning  LotArea  Street  LotShape  LandContour  Utilities  LotConfig  LandSlope   Neighborhood Condition1 Condition2  BldgType  HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd  RoofStyle  RoofMatl Exterior1st Exterior2nd  MasVnrArea  ExterQual  ExterCond  Foundation  BsmtQual  BsmtCond  BsmtExposure  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold SaleType SaleCondition  SalePrice
0   1          60       2.0     8450       1         3            3          3          0          2  197965.734807       Norm       Norm       4.0           7            7            5       2003          2003          4         2     VinylSd     VinylSd       196.0          3          2           5       4.0       3.0           1.0           6.0         706          Unf           0        150          856    GasA        Ex          Y      SBrkr       856       854             0       1710             1             0         2         1             3             1          Gd             8        Typ           0     Attchd       2003.0          RFn           2         548         TA         TA          Y           0           61              0          0            0         0        0       2    2008       WD        Normal     208500
1   2          20       2.0     9600       1         3            3          3          2          2  197643.209810      Feedr       Norm       4.0           4            6            8       1976          1976          4         2     MetalSd     MetalSd         0.0          2          2           4       4.0       3.0           4.0           5.0         978          Unf           0        284         1262    GasA        Ex          Y      SBrkr      1262         0             0       1262             0             1         2         0             3             1          TA             6        Typ           1     Attchd       1976.0          RFn           2         460         TA         TA          Y         298            0              0          0            0         0        0       5    2007       WD        Normal     181500
2   3          60       2.0    11250       1         2            3          3          0          2  197965.734807       Norm       Norm       4.0           7            7            5       2001          2002          4         2     VinylSd     VinylSd       162.0          3          2           5       4.0       3.0           2.0           6.0         486          Unf           0        434          920    GasA        Ex          Y      SBrkr       920       866             0       1786             1             0         2         1             3             1          Gd             6        Typ           1     Attchd       2001.0          RFn           2         608         TA         TA          Y           0           42              0          0            0         0        0       9    2008       WD        Normal     223500
3   4          70       2.0     9550       1         2            3          3          1          2  209344.287867       Norm       Norm       4.0           7            7            5       1915          1970          4         2     Wd Sdng     Wd Shng         0.0          2          2           3       3.0       4.0           1.0           5.0         216          Unf           0        540          756    GasA        Gd          Y      SBrkr       961       756             0       1717             1             0         1         0             3             1          Gd             7        Typ           1     Detchd       1998.0          Unf           3         642         TA         TA          Y           0           35            272          0            0         0        0       2    2006       WD       Abnorml     140000
4   5          60       2.0    14260       1         2            3          3          2          2  318453.591177       Norm       Norm       4.0           7            8            5       2000          2000          4         2     VinylSd     VinylSd       350.0          3          2           5       4.0       3.0           3.0           6.0         655          Unf           0        490         1145    GasA        Ex          Y      SBrkr      1145      1053             0       2198             1             0         2         1             4             1          Gd             9        Typ           1     Attchd       2000.0          RFn           3         836         TA         TA          Y         192           84              0          0            0         0        0      12    2008       WD        Normal     250000